version: "3.7"
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './airflow.cfg:/usr/src/app/airflow/airflow.cfg'
      - '../../src/example:/usr/src/app/example'
    ports:
      - '8080:8080'
